### ISSUE TITLE
Abstract reusable code

### ISSUE THREAD

**Issue by raivivek** [hargup/WIGI-website#13]
A lot of code, for example, writing script files and generating tags is written over and again at the moment.

**Comment by raivivek** [comment]
@notconfusing It'll probably be much cleaner if we specify the path to data directory somewhere and then use the specific csv files relative to that, instead of hard coding the values as in done now.

**Comment by hargup** [comment]
see https://github.com/hargup/WIGI-website/pull/42

**Comment by raivivek** [comment]
Splitting issue.
