### ISSUE TITLE
Style Design Improvement for All Plots

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#18]
- Improvements: 
  - [x] Make all Plots wider to fit the width of where the header text starts and ends.
  - [ ] Rotate Y axes number to horizontal and shif them up to above the Y lines instead of centered on the Y lines. 
  - [ ](If possible) Shift Y lines to be left of Y numbers instesad of right
    - [ ] To compensate make the X axis start negative. So that blank space is inserted between Y axis and instead.
  - [ ] Hide Bokeh tool-bars. And add template line saying "Scroll to zoom".

**Comment by raivivek** [comment]
- Y-axes numbers/labels are already horizontal. I'm not sure how shifting them above the Y lines is going to be useful other than introducing confusion.
- Third point is too much customization/work. Need stronger reasons to introduce it.
- Bokeh toolbar is pretty useful, and I think we understand that they should remain.

Please reopen (in a separate issue) if there is a disagreement.
