### ISSUE TITLE
Style Improvements for Pandas HTML Charts

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#23]
`pandas.DataFrame.to_html()` takes an arguement with path to a css file. I think we could do all these improvements with that and arguments to `to_html()`.
- All charts from Pandas HTML (Done in CSS).
  - More horizontal padding
  - Only hortizontal Lines. And make them merchant:light-grey, except for header line.
  - Sans serif  default font.
  - Width of chart to match width of Graphs and % based column widths. 
  - Size of text more closely matched to graph sizes.
  - Numerical formatting:
    - Format as actual percents
    - Format to 2 decimal places
    - Right align. 
    - Use thousands comma separator

**Comment by raivivek** [comment]
- [x] Scale them appropriately to fit within the container and align/stack as necessary.

**Comment by raivivek** [comment]
The changes should address most of the concerns, except the Numerical formatting one. That involves too low-level, graph specific customization (since rounding off in one table might be useful but give away significance in others, thousands separator)

cc @hargup
