### ISSUE TITLE
Make Gender by language changes plot linear

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#30]
Right now the data looks squashed, will it look better if we make it linear in X axis.

**Comment by raivivek** [comment]
@notconfusing @hargup Linear scale looks even worse because there are a lot of wikis with relatively lower yet similar number of total articles in them. What we can probably do for emphasis is to show only a few based on some cutoff?

**Comment by notconfusing** [comment]
@vivekiitkgp Ok, then implement a cut-off for only the top 50 wikis by bio count. and put in a comment on the page explaining the cut-off.
