### ISSUE TITLE
Gender by language - can we start zoomed in?

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#33]
Is it possible  to have bokeh start zoomed in a specific area of a plot? If so, how?

**Comment by raivivek** [comment]
The plot has improved considerably since the time this issue was created. We have now clear, well separated points with hover functionality. The points are well spanned across the graph and one can _highlight_ a specific area of it by using `Box select` tool present in the widget bar.

**Comment by raivivek** [comment]
Closing!
