### ISSUE TITLE
Gender by country, switch colour palette.

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#35]
Right now the colors all look very similar to each other. Can we "norm" the colorspace, so the lowest sourced country is the first accen color and the hight is the second accent color from the palette?

Palette: https://github.com/hargup/WIGI-website/wiki/Color-Palette 

Bonus: add a legend for colors

**Comment by raivivek** [comment]
The colors looks a bit distinct now. Although, one can definitely argue whether they look pretty. Legend is pending, which I'm moving to a new issue.
