### ISSUE TITLE
Gender by country, Full country names, chart modifications

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#36]
- [x] Full country names in html chart, instead of 2 letter country names.
  - I was using the wikidata property:P297, and preprocessed using this file https://github.com/notconfusing/WIGI/blob/master/helpers/aggregation_maps/qid_p297.json , which you might have to update to also contain english label.
- [ ] And dislpay men and women added total added as well as the currently existing percentage figue.
- [x] For the newest-changes chart, add "change-in" in the header text of the chart.
- [x] Change "score" to "% female" in chart.

**Comment by raivivek** [comment]
3/4 fixed. Moving the rest to #46.
