### ISSUE TITLE
Pandas HTML Charts, split into two if showing top and bottom 10

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#37]
For top ten and Bottom Ten Split into 2 charts, One that is titled " Top Ten" and one "Bottom Ten", and are titled that way.

Right now these are done lazily by calling `.to_html(max_rows=20)`. So make independent DFs for each top and bottom and call `.to_html` on them.

**Comment by raivivek** [comment]
WIP in #40

**Comment by raivivek** [comment]
Closed in #40 .
