### ISSUE TITLE
Make titling fit for all plots

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#39]
See if you can fix Bokeh cutting off long titles. Otherwise (and this may just be the easier option),
pass the title of the plots the template as HTML.

**Comment by raivivek** [comment]
The problem of title wrap is still an open issue in Bokeh's issue tracker. As you suggest, we can either add an HTML heading along with the title or perhaps adopt a non-redundant title value.

For example, when viewing Gender by DOB page, it's already evident that are seeing graphs for Death by Birth and Death criteria. We need not mention it over again.
On the other hand, after adding  `<h2>` titles corresponding to changes and all time text, mentioning these in title again makes it redundant.

Which one seems better? Other options?

**Comment by notconfusing** [comment]
@vivekiitkgp Since title-wrapping isn't fixed in Bokeh right now, lets move all titling to HTML. Kind of a radical move, but that's what we need to do.
