### ISSUE TITLE
Polish UI for the Gender by Country Plot

### ISSUE THREAD

**Issue by hargup** [hargup/WIGI-website#4]
- Colors
- Transparency
- Aspect Ratio

**Comment by raivivek** [comment]
@fsoong Suggest a good color scheme for the world map.

**Comment by raivivek** [comment]
The issue that you wanted to closer perhaps is #5.

**Comment by fsoong** [comment]
@vivekiitkgp Sorry I've been unavailable, do you still need a color scheme?

**Comment by raivivek** [comment]
Indeed. It'll be helpful to have one. :)

## 

Vivek Rai
https://vivekiitkgp.github.io

**Comment by notconfusing** [comment]
Color scheme available here https://github.com/hargup/WIGI-website/wiki/Color-Palette ,
 but this is now covered in a different issue, so closing.
