### ISSUE TITLE
by country 

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#46]
- top-10 and bottom-10,
  - exclude countries that don't a have two-letter code
  - the changes and all-time top 10s are the same
-  color-gradient fix, to spread out colors

**Comment by raivivek** [comment]
Froom #36, 
- [ ] dislpay men and women added total added as well as the currently existing percentage figue.

**Comment by notconfusing** [comment]
- [x] under changes section: hover-over should say "change in wigi" instead of "wigi"
