### ISSUE TITLE
by language

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#48]
- [x] add axis labels
- [x] bokeh title is not removed
- [x] replace wikicode with english name
- [x] top and bottom 10 are the same in changes and all time.
- [x] place "language name" next to dot, so it can be seen without hover over

**Comment by raivivek** [comment]
We need a language to culture map. What is already available is [country to culture map](https://github.com/notconfusing/WIGI/blob/master/helpers/aggregation_maps/country_maps.csv). So either we can prepare a language to country map or the former directly.

Note that direct country to official language map will not be entirely correct except for bigger countries. Consider for example, the culture classification of languages like 'Bengali', 'Punjabi' which have their own Wikipedia and are Indian languages (but not official).

**Comment by notconfusing** [comment]
vivek, coloring by culture is low priority, so lets move on

**Comment by raivivek** [comment]
![wigi-label](https://cloud.githubusercontent.com/assets/3218617/11019563/b241250a-8624-11e5-8340-b20440e891ef.png)

Placing language name doesn't look very neat. Perhaps color scheme will be more informative which we have deferred for later. @hargup What say?

**Comment by hargup** [comment]
@vivekiitkgp maybe you can try placing the language code next to points instead of full names.

**Comment by raivivek** [comment]
@hargup Want to give this a shot?

**Comment by notconfusing** [comment]
Yes, I the screenshot looks great! Let's implement it!
