### ISSUE TITLE
design front page with image and description

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#51]

**Comment by notconfusing** [comment]
<strong>Wi</strong>kipedia <strong>G</strong>ender <strong>I</strong>ndicators (<strong>WIGI</strong>)

![36th_g8_summit_member_cropped_36th_g8_summit_member_20100625_1080](https://cloud.githubusercontent.com/assets/1494283/10463045/bfbe87f4-71a7-11e5-9851-59778a9f9ee0.jpg)
<caption align="bottom">The world's leaders</caption>

WIGI is a project producing a <strong>open data set</strong> about the <em>gender, date of birth, place of birth, ethnicity, occupation</em>, and <em> language</em> of <strong>biography articles</strong> in all Wikipedias. Our <a href="http://wigi.wmflabs.org/snapshot_data/">data set</a> comes from <a href="https://www.wikidata.org/wiki/Wikidata:Main_Page">Wikidata</a>, the database the feeds Wikipedia, and is updated weekly. This site shows a few demonstrations of what can be done with that information. 

This project started as a [personal research interest](http://arxiv.org/abs/1502.03086), and is now [funded by a Wikimedia Foundation Grant](https://meta.wikimedia.org/wiki/Grants:IEG/WIGI:_Wikipedia_Gender_Index).

**Comment by hargup** [comment]
@notconfusing I think the infographic you used at wikimania will much better than this image of almost all male politicians.

![](http://notconfusing.com/wp-content/uploads/2015/07/infographic.png)

**Comment by raivivek** [comment]
@hargup I feel that the infographic is just too large for the main page. May be compacter form of this or a more gender-neutral yet appealing photo?

**Comment by fsoong** [comment]
Yes I'd suggested to Masssly and @notconfusing before to use the photos instead, but I did give options that focus more on showing the women too.
