### ISSUE TITLE
Try out symlog scale on gender by language plot

### ISSUE THREAD

**Issue by hargup** [hargup/WIGI-website#52]
symlog scale is linear near zeros and logarithmic for higher values, it might turn out to be good scale for our plots.

**Comment by raivivek** [comment]
While `symlog` isn't natively supported by Bokeh, having a mixed scale (log on y-axis and linear on x) is turning out to be pretty good.

**Comment by raivivek** [comment]
Pull request #69

**Comment by raivivek** [comment]
Fixed. `log` Y-axis and `linear` X-axis does the trick.
