### ISSUE TITLE
Fix the cron-job, which does not seem to be working.

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#89]
Data is now at Nov 23 and that is more than a week ago. 
& the website is still displaying the Oct 26 - Nov 2 data.

Why is it not updating?

**Comment by raivivek** [comment]
Fixed.

**Comment by notconfusing** [comment]
@vivekrai what was the issue?

**Comment by raivivek** [comment]
The cron job was run by root which didn't know the location of 'nikola`. I
just added a path variable to the cron script.

## 

Vivek Rai
https://vivekiitkgp.github.io
