### ISSUE TITLE
Gender by Culture from Usability Study

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#91]
- [x] Include a column in both Recent changes and All time tables showing percentage of females
- [x] Remove the e+ mathematical notation on the Y-axis and replace them with wholes numbers
- [x] Fix bug: Instead of ten (10) cultures, the tables display only nine (9). In fact if you can just show top 10, without bottom 10 that would be fine.

**Comment by raivivek** [comment]
For point 1, we can also plot the bar chart using percentage figures instead of using absolute numbers. What do you suggest?
@notconfusing

**Comment by notconfusing** [comment]
@vivekiitkgp keep the absolute numbers in the graphs, and just include the % figure in the tables.
