### ISSUE TITLE
Gender by Date of Birth from Usability Study

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#93]
- [x] Help users know they can hover, zoom in and reset chart by eg. including a bold direction in the introductory text (Consult with Max for finalized text).
- [ ] Add a clickable feature for users to be able to concatenate and view years by their choice, eg. by decades, centuries, 400yrs, etc (Is there a way in Bokeh just to change the scale of the X-axis without manipulating the Y-axis?) If so write about how to do it above it.

**Comment by raivivek** [comment]
@notconfusing 
- Probably we can include a small section titled `interacting with the charts` detailing how one can use chart widgets to make sense of the data.


## Interacting with the charts

A number of widgets have been provided with the interactive charts for better understanding of the data. For example, **Hover Tool** allows you to point your cursor over a specific data point and view the exact details, **Box Select Tool** allows you to select and highlight only specific regions of the graph.

We encourage your to use these tools to play around with the charts and observe interesting trends.

- Will not be trivial. Probably should move to an issue titled `enhancement` or something similar.

**Comment by notconfusing** [comment]
@vivekiitkgp I think it's enough to write 1 sentence at the end of the top page text. We don't want to add too much because we don't want to clutter the page. How about.

"Please **hover** and **pan** to interact with graphs".
