### ISSUE TITLE
Gender by Language from Usability Study

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#94]
- [x] Include a fifth column in the table to display actual number of female biographies besides the percentages.
- [x] Add a fourth information "total female", besides the percentage in the hover oevr visualization as well
- [x] Exclude mathematical notation from y plane (in all-time graph).
- [ ]  Add percentage sign to x plane values
- [x] Add note at top about how we choose only the top languages, but that the information can be found in the data section for the adventurous user.
- [x] Make counts in table to begin from One and not Zero

**Comment by raivivek** [comment]
Point 5 is buggy probably due to Bokeh. Considering an alternative design for Point 6.
