### ISSUE TITLE
Page sections from Usability

### ISSUE THREAD

**Issue by notconfusing** [hargup/WIGI-website#96]
- [x] Is it possible to add a left-hand navigation between Recent changes and All time?
- [x]  Increase space between sections

**Comment by raivivek** [comment]
For first, do you mean a table of content kind of navigation?

cc/ @notconfusing

**Comment by raivivek** [comment]
Ping @notconfusing

**Comment by notconfusing** [comment]
Here is how I imagined it:

![vivek mockup](https://cloud.githubusercontent.com/assets/1494283/12096872/4319c12a-b2cd-11e5-87a5-0560f6e53191.jpg)

**Comment by notconfusing** [comment]
@vivekiitkgp

**Comment by notconfusing** [comment]
Done, thanks @vivekiitkgp
